apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.env }}
  namespace: {{ .Values.appName }}-{{ .Values.env }}
spec:
  acme:
    server: {{ .Values.letsencrypt.server}}
    email: jarrodmerryman@gmail.com
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.env }}
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: {{ .Values.azureSubId }}
            resourceGroupName: {{ .Values.appName }}-{{ .Values.env }}-rg
            hostedZoneName: {{ .Values.domainName }}
            environment: AzurePublicCloud
