apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}-{{.Values.env}}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
              - name: {{ .Values.ports.name }}
                containerPort: {{ .Values.ports.targetPort }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.ports.name }}
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.ports.name }}
            initialDelaySeconds: 300
            periodSeconds: 60
          env:
            - name: COSMOS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: cosmos-connect-string
                  key: credential
            - name: FBB_BOT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fbb-bot-client-id
                  key: credential
            - name: FBB_BOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fbb-bot-secret
                  key: credential
            - name: OAUTH_CALLBACK_URL
              value: {{ .Values.callbackUrl}}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-secret
                  key: SESSION_SECRET			
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m" # 500milliCPUs (1/2 CPU)
            limits:
              memory: "128Mi"
              cpu: "100m"
