apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.appName }}-secret
    namespace: {{ .Values.appName }}-{{.Values.env}}
    labels:
        app: {{ .Values.appName }}
type: Opaque
data:
    SESSION_SECRET: "{{- randAlphaNum 24 | nospace -}}"
	