apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}-{{.Values.env}}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.appName }}-{{ .Values.env }}-rg
    service.beta.kubernetes.io/azure-pip-name: {{ .Values.appName }}-{{ .Values.env }}-pip
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.ports.port }}
    protocol: TCP
    name: {{ .Values.ports.name }}
    targetPort: {{ .Values.ports.targetPort }}
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer
