apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}-{{.Values.env}}
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.ports.port }}
    protocol: TCP
    name: {{ .Values.ports.name }}
    targetPort: {{ .Values.ports.targetPort }}
  selector:
    app: {{ .Values.appName }}