apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 80
    protocol: TCP
    name: {{ .Values.appName }}
    targetPort: {{ .Values.targetPort }}
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer