env: 'develop'

appName: efit-web

callbackEndpoint: /auth/redirect

domainName: efit-web.site

image:
  name: jabronious/efit-web
  tag: develop
  pullPolicy: Never

ports:
  port: 443
  targetPort: 3000
  # targetPort: 8443
  name: http
  scheme: HTTP

deployService: true
createNamespace: false

secretEnv:
subdomain:

letsencrypt:
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  env: letsencrypt-staging
