env: 'develop'

appName: 'efit-backend'

callbackUrl: http://localhost:3000/auth/redirect

image:
  name: jabronious/efit-backend
  tag: develop
  pullPolicy: Never

ports:
  port: 80
  targetPort: 3000
  name: http

deployService: true

secretEnv:
