name: Load k8s Secrets

on:
  pull_request:
    branches: [main, staging, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENCODED_OP_CONNECT_TOKEN: ${{ secrets.ENCODED_OP_CONNECT_TOKEN }}
      OP_PASSWORD: ${{ secrets.OP_PASSWORD }}
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - run: |
          eval $(echo “$OP_PASSWORD” | op signin)
          op document get "CRED_FILE" --output=./secret-plans.json
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - uses: azure/aks-set-context@v3
        with:
          resource-group: 'efit-aks-rg'
          cluster-name: 'efit-aks'
