name: Load k8s Secrets

on:
  pull_request:
    branches: [main, staging, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENCODED_OP_CONNECT_TOKEN: ${{ secrets.ENCODED_OP_CONNECT_TOKEN }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Load Secrets
        run: |
          op document get "CRED_FILE" --output=./secret-plans.json
      - name: Auth Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'efit-aks-rg'
          cluster-name: 'efit-aks'
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Run OP Helm
        run: |
          helm repo add 1password https://1password.github.io/connect-helm-charts && \
          helm upgrade --install connect 1password/connect \
          --set-file connect.credentials=./secret-plans.json \
          --set operator.create=true \
          --set operator.token.value="${OP_CONNECT_TOKEN}" \
          --wait
