name: EFIT BACKEND UNIT TESTING

on:
  pull_request:
    branches: [prod, staging, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install --global yarn
      - run: yarn install
      #     - run: npm run build --if-present
      - name: 'Yarn Test And Coverage'
        run: yarn test:cov
